// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXmrq5OuHGFXKNxfVwEXYOxPEnkmfvG0E',
    appId: '1:1010720787698:web:60b7260488451890f2546b',
    messagingSenderId: '1010720787698',
    projectId: 'rentzia',
    authDomain: 'rentzia.firebaseapp.com',
    storageBucket: 'rentzia.firebasestorage.app',
    measurementId: 'G-4JGET3BG5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUL6fJkjpOuxuRyd5NzXefJQv0xMLTxDo',
    appId: '1:1010720787698:android:1cfc0b2aedca92fcf2546b',
    messagingSenderId: '1010720787698',
    projectId: 'rentzia',
    storageBucket: 'rentzia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJhAkwbqkamUxknMzd7Lh5lMlS3EMuzbQ',
    appId: '1:1010720787698:ios:dc0711d62142a555f2546b',
    messagingSenderId: '1010720787698',
    projectId: 'rentzia',
    storageBucket: 'rentzia.firebasestorage.app',
    iosBundleId: 'com.example.hacathon2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJhAkwbqkamUxknMzd7Lh5lMlS3EMuzbQ',
    appId: '1:1010720787698:ios:dc0711d62142a555f2546b',
    messagingSenderId: '1010720787698',
    projectId: 'rentzia',
    storageBucket: 'rentzia.firebasestorage.app',
    iosBundleId: 'com.example.hacathon2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXmrq5OuHGFXKNxfVwEXYOxPEnkmfvG0E',
    appId: '1:1010720787698:web:57633ed3974b5552f2546b',
    messagingSenderId: '1010720787698',
    projectId: 'rentzia',
    authDomain: 'rentzia.firebaseapp.com',
    storageBucket: 'rentzia.firebasestorage.app',
    measurementId: 'G-5VWN3DEX33',
  );
}
